// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/room": {
            "get": {
                "description": "get all rooms",
                "tags": [
                    "room"
                ],
                "summary": "Get all rooms",
                "parameters": [
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RoomResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create room",
                "tags": [
                    "room"
                ],
                "summary": "Create Room",
                "parameters": [
                    {
                        "description": "room",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Room"
                        }
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "int"
                        }
                    }
                }
            }
        },
        "/room/{id}": {
            "get": {
                "description": "get room by id",
                "tags": [
                    "room"
                ],
                "summary": "Get room by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RoomResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "update room",
                "tags": [
                    "room"
                ],
                "summary": "Update room",
                "parameters": [
                    {
                        "description": "update room",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateRoomInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete room",
                "tags": [
                    "room"
                ],
                "summary": "Delete room by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sign-in": {
            "post": {
                "description": "authentication",
                "tags": [
                    "auth"
                ],
                "summary": "Sign in",
                "parameters": [
                    {
                        "description": "Authentication",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Authentication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sign-up": {
            "post": {
                "description": "authorization",
                "tags": [
                    "auth"
                ],
                "summary": "Sign up",
                "parameters": [
                    {
                        "description": "Authorization",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ws/{id}": {
            "get": {
                "description": "join room",
                "tags": [
                    "ws"
                ],
                "summary": "Ws connection with chat room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token getting after joining room",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ws/{id}/join": {
            "post": {
                "description": "join room",
                "tags": [
                    "ws"
                ],
                "summary": "Join chat room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Authentication": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.Room": {
            "type": "object",
            "properties": {
                "creator_id": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "room_id": {
                    "type": "integer"
                }
            }
        },
        "models.RoomResponse": {
            "type": "object",
            "properties": {
                "creator_id": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "room_id": {
                    "type": "integer"
                }
            }
        },
        "models.UpdateRoomInput": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Gotalk API",
	Description:      "This is the chat rest api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
